/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JTextField;
import modelo.Modelo;

/**
 *
 * @author electra
 */
public class InicioW extends javax.swing.JFrame {

    private ControladorInicio control;
    private Modelo modelo;
    private ArrayList<JTextField> arrayTextFields=new ArrayList<JTextField>();
    private ArrayList<JButton> arrayButtons=new ArrayList<JButton>();
    
    public InicioW(Modelo modelo) {
        initComponents();
        this.modelo = modelo;
        control = new ControladorInicio(this,modelo);
        //Añadimos los textfields y los botones a sus respectivos AL
        arrayTextFields.add(inscrito1);
        arrayTextFields.add(inscrito2);
        arrayTextFields.add(inscrito3);
        arrayTextFields.add(inscrito4);
        arrayTextFields.add(inscrito5);
        arrayButtons.add(jButtonEl1);
        arrayButtons.add(jButtonEl2);
        arrayButtons.add(jButtonEl3);
        arrayButtons.add(jButtonEl4);
        arrayButtons.add(jButtonEl5);
        actualiza();
        
    }
    public void actualiza(){
        //Vacia los textfields y pone los botones como no visibles
        for (int j=0;j<5;j++){
            arrayTextFields.get(j).setText("");
            arrayButtons.get(j).setVisible(false);
        }
        for (int i=0;i<modelo.inscritos();i++){
            arrayTextFields.get(i).setText(modelo.getNombre(i));
            arrayButtons.get(i).setVisible(true);
        }
        jTextField1.setText(String.valueOf(modelo.getTotal()));
        buttonAñadir.setEnabled(true);
        if(modelo.inscritos()==5){
            buttonAñadir.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        inscrito1 = new javax.swing.JTextField();
        inscrito2 = new javax.swing.JTextField();
        inscrito3 = new javax.swing.JTextField();
        inscrito4 = new javax.swing.JTextField();
        inscrito5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buttonAñadir = new javax.swing.JButton();
        buttonPagar = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonEl1 = new javax.swing.JButton();
        jButtonEl2 = new javax.swing.JButton();
        jButtonEl3 = new javax.swing.JButton();
        jButtonEl4 = new javax.swing.JButton();
        jButtonEl5 = new javax.swing.JButton();

        jButton6.setText("jButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inscrito1.setEditable(false);

        inscrito2.setEditable(false);

        inscrito3.setEditable(false);

        inscrito4.setEditable(false);

        inscrito5.setEditable(false);

        jLabel1.setText("Inscritos:");

        buttonAñadir.setText("Añadir");
        buttonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAñadirActionPerformed(evt);
            }
        });

        buttonPagar.setText("Pagar");
        buttonPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPagarActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);

        jLabel2.setText("Total:");

        jButtonEl1.setText("X");
        jButtonEl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEl1ActionPerformed(evt);
            }
        });

        jButtonEl2.setText("X");
        jButtonEl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEl2ActionPerformed(evt);
            }
        });

        jButtonEl3.setText("X");
        jButtonEl3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEl3ActionPerformed(evt);
            }
        });

        jButtonEl4.setText("X");
        jButtonEl4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEl4ActionPerformed(evt);
            }
        });

        jButtonEl5.setText("X");
        jButtonEl5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEl5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 53, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonAñadir)
                                .addGap(18, 18, 18)
                                .addComponent(buttonPagar)
                                .addGap(18, 18, 18)
                                .addComponent(buttonCancelar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(inscrito2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEl2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(inscrito3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEl3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(inscrito4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEl4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(inscrito5, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEl5))
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(inscrito1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEl1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonAñadir, buttonCancelar, buttonPagar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inscrito1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEl1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inscrito2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEl2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inscrito3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEl3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inscrito4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEl4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inscrito5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEl5))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAñadir)
                    .addComponent(buttonPagar)
                    .addComponent(buttonCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAñadirActionPerformed
       control.añadir();
       
    }//GEN-LAST:event_buttonAñadirActionPerformed

    private void buttonPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPagarActionPerformed
        control.pagar();
    }//GEN-LAST:event_buttonPagarActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
       control.cancelar();
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void jButtonEl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEl1ActionPerformed
        control.eliminaParticipante(0);
    }//GEN-LAST:event_jButtonEl1ActionPerformed

    private void jButtonEl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEl2ActionPerformed
        control.eliminaParticipante(1);
    }//GEN-LAST:event_jButtonEl2ActionPerformed

    private void jButtonEl3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEl3ActionPerformed
        control.eliminaParticipante(2);
    }//GEN-LAST:event_jButtonEl3ActionPerformed

    private void jButtonEl4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEl4ActionPerformed
        control.eliminaParticipante(3);
    }//GEN-LAST:event_jButtonEl4ActionPerformed

    private void jButtonEl5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEl5ActionPerformed
        control.eliminaParticipante(4);
    }//GEN-LAST:event_jButtonEl5ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAñadir;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonPagar;
    private javax.swing.JTextField inscrito1;
    private javax.swing.JTextField inscrito2;
    private javax.swing.JTextField inscrito3;
    private javax.swing.JTextField inscrito4;
    private javax.swing.JTextField inscrito5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonEl1;
    private javax.swing.JButton jButtonEl2;
    private javax.swing.JButton jButtonEl3;
    private javax.swing.JButton jButtonEl4;
    private javax.swing.JButton jButtonEl5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
