/*
 *Entrega IPC. Ventana de configuracion de pantalla
 * @author Ester Diego
 * @author Adrian Del Prado
 */
package confpantalla.Vista;

import confpantalla.Modelo.ModeloCP;
import java.awt.AWTException;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;

/**
 *
 * @author Ester Diego
 * @author Adrian Del Prado
 */
public class VistaCP extends javax.swing.JFrame {

    ControladorCP control;
    ModeloCP modelo;
    
    
    
    public VistaCP() {
        
        modelo = new ModeloCP();
        control = new ControladorCP(this,modelo);
        initComponents();
        control.verCompatibles();
        jLabelBrilloPro.setText(String.valueOf(modelo.getBrillo())+"%");
        jLabelContrPro.setText(String.valueOf(modelo.getContraste())+"%");
        jButtonAplicar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelBrilloContr = new javax.swing.JPanel();
        jSliderBrillo = new javax.swing.JSlider();
        jSliderContraste = new javax.swing.JSlider();
        jLabelBrillo = new javax.swing.JLabel();
        jLabelContraste = new javax.swing.JLabel();
        jLabelBrilloPro = new javax.swing.JLabel();
        jLabelContrPro = new javax.swing.JLabel();
        jPanelGiro = new javax.swing.JPanel();
        giroHor = new javax.swing.JRadioButton();
        giroVert = new javax.swing.JRadioButton();
        giroHorInvert = new javax.swing.JRadioButton();
        giroVertInvert = new javax.swing.JRadioButton();
        jPanelResolucion = new javax.swing.JPanel();
        jComboBoxResolucion = new javax.swing.JComboBox();
        jPanelColores = new javax.swing.JPanel();
        jComboBoxColores = new javax.swing.JComboBox();
        etiqResolucion = new javax.swing.JLabel();
        etiqColores = new javax.swing.JLabel();
        etiqGiro = new javax.swing.JLabel();
        jButtonAplicar = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelNotificacion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelImagen = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Opciones de pantalla");

        jPanelBrilloContr.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jSliderBrillo.setPaintTicks(true);
        jSliderBrillo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderBrilloStateChanged(evt);
            }
        });

        jSliderContraste.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderContrasteStateChanged(evt);
            }
        });

        jLabelBrillo.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabelBrillo.setText("Brillo");

        jLabelContraste.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabelContraste.setText("Contraste");

        jLabelBrilloPro.setText("jLabel1");

        jLabelContrPro.setText("jLabel2");

        javax.swing.GroupLayout jPanelBrilloContrLayout = new javax.swing.GroupLayout(jPanelBrilloContr);
        jPanelBrilloContr.setLayout(jPanelBrilloContrLayout);
        jPanelBrilloContrLayout.setHorizontalGroup(
            jPanelBrilloContrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBrilloContrLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBrilloContrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBrilloContrLayout.createSequentialGroup()
                        .addComponent(jLabelContraste)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSliderContraste, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
                    .addGroup(jPanelBrilloContrLayout.createSequentialGroup()
                        .addComponent(jLabelBrillo)
                        .addGap(30, 30, 30)
                        .addComponent(jSliderBrillo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelBrilloContrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelContrPro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelBrilloPro, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelBrilloContrLayout.setVerticalGroup(
            jPanelBrilloContrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBrilloContrLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelBrilloContrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBrilloContrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelBrillo)
                        .addComponent(jLabelBrilloPro))
                    .addComponent(jSliderBrillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanelBrilloContrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBrilloContrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelContraste)
                        .addComponent(jLabelContrPro))
                    .addComponent(jSliderContraste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelGiro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        buttonGroup1.add(giroHor);
        giroHor.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        giroHor.setSelected(true);
        giroHor.setText("Horizontal (0º)");
        giroHor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                giroHorStateChanged(evt);
            }
        });

        buttonGroup1.add(giroVert);
        giroVert.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        giroVert.setText("Vertical (90º)");

        buttonGroup1.add(giroHorInvert);
        giroHorInvert.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        giroHorInvert.setText("Horizontal invertido(180º)");

        buttonGroup1.add(giroVertInvert);
        giroVertInvert.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        giroVertInvert.setText("Vertical invertido (270º)");
        giroVertInvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giroVertInvertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGiroLayout = new javax.swing.GroupLayout(jPanelGiro);
        jPanelGiro.setLayout(jPanelGiroLayout);
        jPanelGiroLayout.setHorizontalGroup(
            jPanelGiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGiroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(giroHor)
                    .addComponent(giroVert)
                    .addComponent(giroHorInvert)
                    .addComponent(giroVertInvert))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelGiroLayout.setVerticalGroup(
            jPanelGiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGiroLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(giroHor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(giroVert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(giroHorInvert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(giroVertInvert)
                .addGap(16, 16, 16))
        );

        jPanelResolucion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jComboBoxResolucion.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jComboBoxResolucion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1920x1080", "1152x768", "1024x768", "896x600", "800x600" }));
        jComboBoxResolucion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxResolucionItemStateChanged(evt);
            }
        });
        jComboBoxResolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxResolucionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelResolucionLayout = new javax.swing.GroupLayout(jPanelResolucion);
        jPanelResolucion.setLayout(jPanelResolucionLayout);
        jPanelResolucionLayout.setHorizontalGroup(
            jPanelResolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResolucionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBoxResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanelResolucionLayout.setVerticalGroup(
            jPanelResolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResolucionLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jComboBoxResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanelColores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jComboBoxColores.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jComboBoxColores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "16", "32" }));
        jComboBoxColores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxColoresItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanelColoresLayout = new javax.swing.GroupLayout(jPanelColores);
        jPanelColores.setLayout(jPanelColoresLayout);
        jPanelColoresLayout.setHorizontalGroup(
            jPanelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColoresLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jComboBoxColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanelColoresLayout.setVerticalGroup(
            jPanelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColoresLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jComboBoxColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        etiqResolucion.setText("Resolución");

        etiqColores.setText("Colores");

        etiqGiro.setText("Giro");

        jButtonAplicar.setText("Aplicar");
        jButtonAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAplicarActionPerformed(evt);
            }
        });

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Opciones de pantalla:");

        javax.swing.GroupLayout jPanelImagenLayout = new javax.swing.GroupLayout(jPanelImagen);
        jPanelImagen.setLayout(jPanelImagenLayout);
        jPanelImagenLayout.setHorizontalGroup(
            jPanelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelImagenLayout.setVerticalGroup(
            jPanelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonCancelar)
                                .addGap(36, 36, 36)
                                .addComponent(jButtonAplicar))
                            .addComponent(jLabelNotificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jPanelBrilloContr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiqGiro)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanelResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etiqResolucion))
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiqColores)
                                    .addComponent(jPanelColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelGiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBrilloContr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiqGiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelGiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiqColores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiqResolucion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(jLabelNotificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonAplicar))
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void giroVertInvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giroVertInvertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giroVertInvertActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        control.aceptar();
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        control.cancelar();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAplicarActionPerformed
        control.aplicar();
    }//GEN-LAST:event_jButtonAplicarActionPerformed

    private void jSliderBrilloStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderBrilloStateChanged
        control.actualizarTR();
    }//GEN-LAST:event_jSliderBrilloStateChanged

    private void jSliderContrasteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderContrasteStateChanged
        control.actualizarTR();
    }//GEN-LAST:event_jSliderContrasteStateChanged

    private void jComboBoxResolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxResolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxResolucionActionPerformed

    private void giroHorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_giroHorStateChanged
        control.actualizarTR();
    }//GEN-LAST:event_giroHorStateChanged

    private void jComboBoxResolucionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxResolucionItemStateChanged
        control.actualizarTR();
    }//GEN-LAST:event_jComboBoxResolucionItemStateChanged

    private void jComboBoxColoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxColoresItemStateChanged
        control.actualizarTR();
    }//GEN-LAST:event_jComboBoxColoresItemStateChanged

    /**
     * @author Ester Diego
     * @author Adrian Del Prado
     * Actualiza la vista con los nuevos valores del modelo al pulsar Aplicar o Aceptar
     */
    public void actualizar(){
        jSliderBrillo.setValue(modelo.getBrilloPro());
        jSliderContraste.setValue(modelo.getContrPro());
        jComboBoxColores.setSelectedItem(modelo.getColorPro());
        jLabelNotificacion.setText("Valores actuales: Brillo:"+modelo.getBrillo()+
                " Contraste:"+modelo.getContraste()+"\n Giro:"+modelo.getGiro()+
                " Resolucion:"+modelo.getResolucion()+" Color:"+modelo.getColor()+" bits");
        jLabelContrPro.setText(String.valueOf(modelo.getContrPro())+"%");
        jLabelBrilloPro.setText(String.valueOf(modelo.getBrilloPro())+"%");
        if(modelo.getCambiado()){
            jButtonAplicar.setEnabled(true);
        }else{
            jButtonAplicar.setEnabled(false);
        }
        
        
    }
    
    
    /**
     * @author Ester Diego
     * @author Adrian Del Prado
     * @return Retornan los valores actuales de las propiedades de la vista
     */
    public int getBrillo(){
        return jSliderBrillo.getValue();
    }
    public int getContraste(){
        return jSliderContraste.getValue();
    }
    public int getGiro(){
        int g = 0;
        
        if(giroHor.isSelected()){
            g = 0;
        }
        if(giroHorInvert.isSelected()){
            g = 180;
        }
        if(giroVert.isSelected()){
            g = 90;
        }
        if(giroVertInvert.isSelected()){
            g = 270;
        }
        return g;
    }
    public int getColor(){
        return Integer.valueOf(String.valueOf(jComboBoxColores.getSelectedItem()));
    }
    public String getResolucion(){
        return String.valueOf(jComboBoxResolucion.getSelectedItem());
    }
    public String getResCombo(int index){
        return jComboBoxResolucion.getItemAt(index).toString();
    }
    public int getResComboTam(){
        return jComboBoxResolucion.getItemCount();
    }
    public int getColCombo(int index){
        return Integer.valueOf(jComboBoxColores.getItemAt(index).toString());
    }
    public int getColComboTam(){
        return jComboBoxColores.getItemCount();
    }
    
    //Modifica quitando elementos incompatibles de colores y resoluciones
    public void quitaElementoResCombo(int index){
        jComboBoxResolucion.removeItemAt(index);
    }
    public void quitaElementoColCombo(int index){
        jComboBoxColores.removeItemAt(index);
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel etiqColores;
    private javax.swing.JLabel etiqGiro;
    private javax.swing.JLabel etiqResolucion;
    private javax.swing.JRadioButton giroHor;
    private javax.swing.JRadioButton giroHorInvert;
    private javax.swing.JRadioButton giroVert;
    private javax.swing.JRadioButton giroVertInvert;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonAplicar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox jComboBoxColores;
    private javax.swing.JComboBox jComboBoxResolucion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBrillo;
    private javax.swing.JLabel jLabelBrilloPro;
    private javax.swing.JLabel jLabelContrPro;
    private javax.swing.JLabel jLabelContraste;
    private javax.swing.JLabel jLabelNotificacion;
    private javax.swing.JPanel jPanelBrilloContr;
    private javax.swing.JPanel jPanelColores;
    private javax.swing.JPanel jPanelGiro;
    private javax.swing.JPanel jPanelImagen;
    private javax.swing.JPanel jPanelResolucion;
    private javax.swing.JSlider jSliderBrillo;
    private javax.swing.JSlider jSliderContraste;
    // End of variables declaration//GEN-END:variables
}
